from __future__ import annotations

from app.config import Settings
from app.domain.rwa import (
    ActionLink,
    ActionReadiness,
    ActionType,
    AssetStatus,
    AssetTemplate,
    AssetType,
    HashKeyChainConfig,
    LiveReadiness,
    OracleFeedConfig,
    TruthLevel,
)
from app.i18n import text_for_locale
from app.rwa.explorer_service import token_url

HASHKEY_DOCS_BASE = "https://docs.hashkeychain.net"
HASHKEY_NETWORK_INFO_URL = (
    f"{HASHKEY_DOCS_BASE}/docs/Build-on-HashKey-Chain/network-info"
)
HASHKEY_TOKEN_CONTRACTS_URL = (
    f"{HASHKEY_DOCS_BASE}/docs/Build-on-HashKey-Chain/Token-Contracts"
)
HASHKEY_KYC_URL = f"{HASHKEY_DOCS_BASE}/docs/Build-on-HashKey-Chain/Tools/KYC"
HASHKEY_ORACLE_URL = f"{HASHKEY_DOCS_BASE}/docs/Build-on-HashKey-Chain/Tools/Oracle"
HASHKEY_SUBGRAPH_URL = (
    f"{HASHKEY_DOCS_BASE}/docs/Build-on-HashKey-Chain/Tools/Subgraph"
)
HASHKEY_ABOUT_URL = f"{HASHKEY_DOCS_BASE}/docs/About-HashKey-Chain"
HASHKEY_CPIC_MMF_URL = (
    "https://www.prnewswire.com/news-releases/"
    "cpic-estable-mmf-launches-on-hashkey-chain-with-100m-first-day-subscriptions-302408505.html"
)
HASHKEY_SILVER_RWA_URL = (
    "https://group.hashkey.com/en/newsroom/"
    "hashkey-chain-supports-the-onchain-issuance-of-hk-s-first-regulated-silverbacked-rwa-token"
)

HASHKEY_ORACLE_FEEDS = [
    OracleFeedConfig(
        feed_id="btc-usd",
        pair="BTC/USD",
        docs_url=HASHKEY_ORACLE_URL,
        testnet_address="0x64697A6Abb508079687465FA9EF99D2Da955D791",
        mainnet_address="0x204ED500ab56A2E19B051561258E3A45c850360F",
    ),
    OracleFeedConfig(
        feed_id="usdt-usd",
        pair="USDT/USD",
        docs_url=HASHKEY_ORACLE_URL,
        testnet_address="0xC45D520D18A465Ec23eE99A58Dc4cB96b357E744",
    ),
    OracleFeedConfig(
        feed_id="usdc-usd",
        pair="USDC/USD",
        docs_url=HASHKEY_ORACLE_URL,
        testnet_address="0xCdB10dC9dB30B6ef2a63aB4460263655808fAE27",
        mainnet_address="0x823d7f90f7A3498DB6595886b6B5dC95E6B0B7f3",
    ),
]


def _asset_action_links(
    chain_config: HashKeyChainConfig,
    *,
    primary_source_url: str = "",
    contract_address: str = "",
    contract_network: str = "mainnet",
) -> list[ActionLink]:
    links: list[ActionLink] = []
    if primary_source_url:
        links.append(ActionLink(kind="docs", label="Docs", url=primary_source_url))
    if contract_address:
        links.append(
            ActionLink(
                kind="contract",
                label="Contract",
                url=token_url(chain_config, contract_network, contract_address),
            )
        )
    return links


def build_chain_config(settings: Settings) -> HashKeyChainConfig:
    testnet_plan_registry_address = settings.hashkey_testnet_plan_registry_address or ""
    mainnet_plan_registry_address = settings.hashkey_mainnet_plan_registry_address or ""
    testnet_kyc_sbt_address = settings.hashkey_testnet_kyc_sbt_address or ""
    mainnet_kyc_sbt_address = settings.hashkey_mainnet_kyc_sbt_address or ""

    return HashKeyChainConfig(
        default_execution_network=(
            "mainnet"
            if settings.hashkey_default_execution_network == "mainnet"
            else "testnet"
        ),
        testnet_chain_id=settings.hashkey_testnet_chain_id,
        testnet_rpc_url=settings.hashkey_testnet_rpc_url,
        testnet_explorer_url=settings.hashkey_testnet_explorer_url,
        mainnet_chain_id=settings.hashkey_mainnet_chain_id,
        mainnet_rpc_url=settings.hashkey_mainnet_rpc_url,
        mainnet_explorer_url=settings.hashkey_mainnet_explorer_url,
        plan_registry_address=testnet_plan_registry_address or mainnet_plan_registry_address,
        kyc_sbt_address=testnet_kyc_sbt_address or mainnet_kyc_sbt_address,
        testnet_plan_registry_address=testnet_plan_registry_address,
        mainnet_plan_registry_address=mainnet_plan_registry_address,
        testnet_kyc_sbt_address=testnet_kyc_sbt_address,
        mainnet_kyc_sbt_address=mainnet_kyc_sbt_address,
        docs_urls=[
            HASHKEY_ABOUT_URL,
            HASHKEY_NETWORK_INFO_URL,
            HASHKEY_TOKEN_CONTRACTS_URL,
            HASHKEY_KYC_URL,
            HASHKEY_ORACLE_URL,
            HASHKEY_SUBGRAPH_URL,
        ],
        oracle_feeds=HASHKEY_ORACLE_FEEDS,
    )


def build_asset_library(
    chain_config: HashKeyChainConfig,
    *,
    locale: str = "zh",
) -> list[AssetTemplate]:
    chain_id = chain_config.mainnet_chain_id
    return [
        AssetTemplate(
            asset_id="hsk-usdt",
            symbol="USDT",
            name="HashKey USDT",
            asset_type=AssetType.STABLECOIN,
            description=text_for_locale(
                locale,
                "HashKey Chain 官方列出的主网 USDT 合约，适合作为稳定币收益与流动性基准。",
                "The mainnet USDT contract listed by HashKey Chain, suitable as the baseline for stablecoin carry and liquidity.",
            ),
            issuer="Tether / bridge representation",
            custody="Bridge-backed ERC20 on HashKey Chain",
            chain_id=chain_id,
            contract_address="0xf1b50ed67a9e2cc94ad3c477779e2d4cbfff9029",
            settlement_asset="USDT",
            execution_style="erc20",
            benchmark_apy=0.055,
            expected_return_low=0.032,
            expected_return_base=0.052,
            expected_return_high=0.068,
            price_volatility=0.015,
            max_drawdown_180d=0.02,
            avg_daily_volume_usd=4_600_000,
            redemption_days=0,
            lockup_days=0,
            management_fee_bps=35,
            entry_fee_bps=0,
            exit_fee_bps=0,
            slippage_bps=6,
            depeg_events_90d=1,
            worst_depeg_bps_90d=38,
            issuer_disclosure_score=0.7,
            custody_disclosure_score=0.68,
            audit_disclosure_score=0.62,
            contract_is_upgradeable=True,
            has_admin_key=True,
            oracle_count=2,
            oracle_sources=["HashKey Oracle / APRO", "secondary market"],
            requires_kyc_level=0,
            minimum_ticket_usd=100,
            tags=["stablecoin", "liquidity", "yield-base"],
            thesis=text_for_locale(
                locale,
                "适合作为流动性底仓和低波动收益腿，但需要显式看待脱锚与赎回信心风险。",
                "Works as the liquidity anchor and lower-volatility carry sleeve, but depeg and redemption-confidence risk must stay explicit.",
            ),
            fit_summary=text_for_locale(
                locale,
                "更适合保守或均衡型配置，重点承担现金管理和出入金缓冲角色。",
                "Best suited to conservative or balanced allocations as the cash-management and liquidity-buffer sleeve.",
            ),
            evidence_urls=[HASHKEY_TOKEN_CONTRACTS_URL, HASHKEY_NETWORK_INFO_URL],
            primary_source_url=HASHKEY_TOKEN_CONTRACTS_URL,
            onchain_verified=True,
            issuer_disclosed=True,
            featured=True,
            statuses=[AssetStatus.PRODUCTION, AssetStatus.VERIFIED],
            truth_level=TruthLevel.ONCHAIN_VERIFIED,
            live_readiness=LiveReadiness.READY,
            default_rank_eligible=True,
            status_explanation=text_for_locale(
                locale,
                "生产可用的链上稳定币基准，合约地址可核验，可直接作为流动性底仓候选。",
                "Production-ready onchain stablecoin baseline with a verifiable contract and direct liquidity-bucket utility.",
            ),
            truth_level_explanation=text_for_locale(
                locale,
                "核心事实来自 HashKey 官方网络文档与链上合约地址，可做链上交叉验证。",
                "Core facts come from HashKey network docs plus an onchain contract address that can be cross-verified.",
            ),
            action_type=ActionType.HOLD,
            action_readiness=ActionReadiness.READY,
            action_links=_asset_action_links(
                chain_config,
                primary_source_url=HASHKEY_TOKEN_CONTRACTS_URL,
                contract_address="0xf1b50ed67a9e2cc94ad3c477779e2d4cbfff9029",
            ),
            execution_notes=[
                text_for_locale(
                    locale,
                    "确认钱包网络在 HashKey Chain 主网，并核对目标合约地址。",
                    "Confirm the wallet is on HashKey Chain mainnet and verify the target contract address.",
                ),
                text_for_locale(
                    locale,
                    "若通过桥接或二级路径建仓，先检查滑点与授权额度。",
                    "If entering via bridge or secondary routing, check slippage and allowance scope first.",
                ),
            ],
            issuer_model="Bridge-backed ERC20 token issued by Tether on HashKey Chain",
            holder_eligibility_note="No KYC requirement; open to all wallet holders",
            transfer_compliance_note="Freely transferable ERC20; subject to bridge operator controls",
            redemption_custody_note="Redeemable via secondary markets or bridge; no lockup",
        ),
        AssetTemplate(
            asset_id="hsk-usdc",
            symbol="USDC",
            name="HashKey USDC",
            asset_type=AssetType.STABLECOIN,
            description=text_for_locale(
                locale,
                "HashKey Chain 官方列出的主网 Bridged USDC，可作为稳定币与 MMF 的比较基准。",
                "The bridged mainnet USDC listed by HashKey Chain, useful as the comparison baseline for stablecoins and MMFs.",
            ),
            issuer="Circle / bridged deployment",
            custody="Bridged USDC on HashKey Chain",
            chain_id=chain_id,
            contract_address="0x054ed45810DbBAb8B27668922D110669c9D88D0a",
            settlement_asset="USDC",
            execution_style="erc20",
            benchmark_apy=0.052,
            expected_return_low=0.03,
            expected_return_base=0.049,
            expected_return_high=0.064,
            price_volatility=0.012,
            max_drawdown_180d=0.018,
            avg_daily_volume_usd=3_800_000,
            redemption_days=0,
            lockup_days=0,
            management_fee_bps=28,
            entry_fee_bps=0,
            exit_fee_bps=0,
            slippage_bps=5,
            depeg_events_90d=1,
            worst_depeg_bps_90d=26,
            issuer_disclosure_score=0.78,
            custody_disclosure_score=0.76,
            audit_disclosure_score=0.75,
            contract_is_upgradeable=False,
            has_admin_key=False,
            oracle_count=2,
            oracle_sources=["HashKey Oracle / APRO", "secondary market"],
            requires_kyc_level=0,
            minimum_ticket_usd=100,
            tags=["stablecoin", "liquidity", "benchmark"],
            thesis=text_for_locale(
                locale,
                "在披露质量和二级流动性上通常优于一般桥接资产，适合做高流动性配置基线。",
                "Usually offers stronger disclosure quality and secondary liquidity than generic bridged assets, making it a high-liquidity baseline.",
            ),
            fit_summary=text_for_locale(
                locale,
                "适合看重 T+0 可退出和低回撤的人群。",
                "Best for users who prioritize T+0 exits and low drawdown.",
            ),
            evidence_urls=[HASHKEY_TOKEN_CONTRACTS_URL, HASHKEY_NETWORK_INFO_URL],
            primary_source_url=HASHKEY_TOKEN_CONTRACTS_URL,
            onchain_verified=True,
            issuer_disclosed=True,
            featured=True,
            statuses=[AssetStatus.PRODUCTION, AssetStatus.VERIFIED],
            truth_level=TruthLevel.ONCHAIN_VERIFIED,
            live_readiness=LiveReadiness.READY,
            default_rank_eligible=True,
            status_explanation=text_for_locale(
                locale,
                "生产可用的链上稳定币基线，适合与 MMF 或 permissioned RWA 做流动性比较。",
                "Production-ready onchain stablecoin baseline suited for liquidity comparisons against MMFs or permissioned RWAs.",
            ),
            truth_level_explanation=text_for_locale(
                locale,
                "储备与合约事实主要来自官方文档和链上可验证地址。",
                "Reserve and contract facts are primarily grounded in official docs and verifiable onchain addresses.",
            ),
            action_type=ActionType.HOLD,
            action_readiness=ActionReadiness.READY,
            action_links=_asset_action_links(
                chain_config,
                primary_source_url=HASHKEY_TOKEN_CONTRACTS_URL,
                contract_address="0x054ed45810DbBAb8B27668922D110669c9D88D0a",
            ),
            execution_notes=[
                text_for_locale(
                    locale,
                    "适合作为现金管理或待机仓位，执行前重点看路由深度和桥接来源。",
                    "Useful as a cash-management sleeve; focus execution checks on route depth and bridge provenance.",
                ),
            ],
            issuer_model="Bridged USDC issued by Circle with reserve attestation program",
            holder_eligibility_note="No KYC requirement; open to all wallet holders",
            transfer_compliance_note="Freely transferable ERC20; Circle may blacklist specific addresses",
            redemption_custody_note="Secondary market exit only; primary redemption through Circle requires KYB",
        ),
        AssetTemplate(
            asset_id="cpic-estable-mmf",
            symbol="MMF",
            name="CPIC Estable MMF",
            asset_type=AssetType.MMF,
            description=text_for_locale(
                locale,
                "HashKey Chain 生态中披露的 tokenized USD MMF 示例，用于短久期高质量货币市场工具配置演示。",
                "A tokenized USD MMF example disclosed in the HashKey Chain ecosystem for short-duration, high-quality money-market allocations.",
            ),
            issuer="CPIC Investment Management / Estable",
            custody="Issuer-managed RWA custody and transfer agent stack",
            chain_id=chain_id,
            contract_address="",
            settlement_asset="USDT",
            execution_style="issuer_portal",
            benchmark_apy=0.048,
            expected_return_low=0.035,
            expected_return_base=0.046,
            expected_return_high=0.055,
            price_volatility=0.025,
            max_drawdown_180d=0.03,
            avg_daily_volume_usd=1_250_000,
            redemption_days=2,
            lockup_days=0,
            management_fee_bps=70,
            entry_fee_bps=10,
            exit_fee_bps=15,
            slippage_bps=0,
            issuer_disclosure_score=0.82,
            custody_disclosure_score=0.8,
            audit_disclosure_score=0.72,
            contract_is_upgradeable=False,
            has_admin_key=False,
            oracle_count=1,
            oracle_sources=["NAV / issuer disclosure"],
            requires_kyc_level=2,
            minimum_ticket_usd=10_000,
            tags=["rwa", "mmf", "professional-investor"],
            thesis=text_for_locale(
                locale,
                "适合作为高流动性与收益平衡型配置，但对申赎节奏、KYC 与发行人执行依赖更强。",
                "Works as a balance between liquidity and carry, but depends more heavily on redemption cadence, KYC gating, and issuer execution.",
            ),
            fit_summary=text_for_locale(
                locale,
                "更适合中低风险偏好、可接受 T+2 资金周转的人群。",
                "Better for lower-risk users who can tolerate roughly T+2 capital turnover.",
            ),
            evidence_urls=[HASHKEY_CPIC_MMF_URL, HASHKEY_KYC_URL],
            primary_source_url=HASHKEY_CPIC_MMF_URL,
            onchain_verified=False,
            issuer_disclosed=True,
            featured=True,
            statuses=[AssetStatus.PRODUCTION, AssetStatus.ISSUER_DISCLOSED],
            truth_level=TruthLevel.ISSUER_DISCLOSED,
            live_readiness=LiveReadiness.PARTIAL,
            default_rank_eligible=True,
            status_explanation=text_for_locale(
                locale,
                "面向真实 RWA 配置场景的发行人披露型资产，但申购和赎回仍依赖发行方入口。",
                "A production-intent issuer-disclosed RWA, but subscription and redemption still depend on the issuer workflow.",
            ),
            truth_level_explanation=text_for_locale(
                locale,
                "主要事实来自发行方和生态披露，链上只能验证部分辅助信息。",
                "Most facts come from issuer and ecosystem disclosure, while only limited support data is verifiable onchain.",
            ),
            action_type=ActionType.SUBSCRIBE,
            action_readiness=ActionReadiness.PARTIAL,
            action_links=_asset_action_links(
                chain_config,
                primary_source_url=HASHKEY_CPIC_MMF_URL,
            ),
            action_blocker_reasons=[
                text_for_locale(
                    locale,
                    "需要更高等级 KYC / 专业投资者资格。",
                    "Requires higher-tier KYC / professional-investor eligibility.",
                ),
                text_for_locale(
                    locale,
                    "暂无公开链上申购合约，需走发行方或平台入口。",
                    "No public onchain subscription contract is exposed; execution depends on the issuer or platform portal.",
                ),
            ],
            execution_notes=[
                text_for_locale(
                    locale,
                    "先确认白名单、最小申购门槛和结算币种，再进入发行人流程。",
                    "Confirm whitelist status, minimum ticket, and settlement currency before entering the issuer flow.",
                ),
                text_for_locale(
                    locale,
                    "退出节奏应按 T+2 处理，流动性要求更高时不应把它当作现金替代。",
                    "Treat exits as T+2; do not use it as a cash substitute when liquidity needs are tighter.",
                ),
            ],
            issuer_model="Regulated MMF managed by CPIC Investment Management via Estable platform",
            holder_eligibility_note="Requires KYC level 2 (professional investor); minimum ticket $10,000",
            transfer_compliance_note="Transfer restricted to whitelisted addresses per issuer compliance policy",
            redemption_custody_note="T+2 redemption via issuer portal; custody managed by issuer transfer agent",
        ),
        AssetTemplate(
            asset_id="hk-regulated-silver",
            symbol="SILV",
            name="Hong Kong Regulated Silver RWA",
            asset_type=AssetType.PRECIOUS_METAL,
            description=text_for_locale(
                locale,
                "基于香港受监管白银 RWA 的演示模板，强调 1:1 实物映射、第三方金库托管与专业投资者门槛。",
                "A demo template for a Hong Kong regulated silver RWA, emphasizing 1:1 metal backing, third-party vault custody, and professional-investor gating.",
            ),
            issuer="HashKey Chain ecosystem issuer",
            custody="Third-party vault custody for .9999 silver",
            chain_id=chain_id,
            contract_address="",
            settlement_asset="USDT",
            execution_style="issuer_portal",
            benchmark_apy=0.022,
            expected_return_low=-0.08,
            expected_return_base=0.065,
            expected_return_high=0.18,
            price_volatility=0.24,
            max_drawdown_180d=0.19,
            avg_daily_volume_usd=420_000,
            redemption_days=3,
            lockup_days=0,
            management_fee_bps=85,
            entry_fee_bps=20,
            exit_fee_bps=25,
            slippage_bps=30,
            issuer_disclosure_score=0.74,
            custody_disclosure_score=0.88,
            audit_disclosure_score=0.7,
            contract_is_upgradeable=False,
            has_admin_key=False,
            oracle_count=1,
            oracle_sources=["spot silver / issuer valuation"],
            requires_kyc_level=2,
            minimum_ticket_usd=5_000,
            tags=["rwa", "precious-metal", "inflation-hedge"],
            thesis=text_for_locale(
                locale,
                "适合作为通胀对冲和分散化腿，但收益分布更宽、流动性与托管条款必须单独审视。",
                "Useful as an inflation-hedge and diversification sleeve, but its broader return distribution and custody/liquidity terms need separate review.",
            ),
            fit_summary=text_for_locale(
                locale,
                "更适合均衡到进取型配置，用于补充与稳定币/MMF 不同的风险收益来源。",
                "Best for balanced-to-aggressive allocations as a return source that differs from stablecoins and MMFs.",
            ),
            evidence_urls=[HASHKEY_SILVER_RWA_URL, HASHKEY_KYC_URL],
            primary_source_url=HASHKEY_SILVER_RWA_URL,
            onchain_verified=False,
            issuer_disclosed=True,
            featured=True,
            statuses=[AssetStatus.PRODUCTION, AssetStatus.ISSUER_DISCLOSED],
            truth_level=TruthLevel.ISSUER_DISCLOSED,
            live_readiness=LiveReadiness.PARTIAL,
            default_rank_eligible=True,
            status_explanation=text_for_locale(
                locale,
                "生产意图明确的金属 RWA 模板，适合做通胀对冲比较，但依旧依赖发行方条款和托管披露。",
                "A production-intent metals RWA suited for inflation-hedge comparisons, but still dependent on issuer terms and custody disclosure.",
            ),
            truth_level_explanation=text_for_locale(
                locale,
                "核心 backing 与托管事实来自发行方披露，尚非全量链上可核验。",
                "Core backing and custody facts come from issuer disclosure rather than full onchain verification.",
            ),
            action_type=ActionType.SUBSCRIBE,
            action_readiness=ActionReadiness.PARTIAL,
            action_links=_asset_action_links(
                chain_config,
                primary_source_url=HASHKEY_SILVER_RWA_URL,
            ),
            action_blocker_reasons=[
                text_for_locale(
                    locale,
                    "需要专业投资者资格与白名单准入。",
                    "Requires professional-investor eligibility and whitelist access.",
                ),
                text_for_locale(
                    locale,
                    "赎回和交收条款需要通过发行方渠道确认。",
                    "Redemption and settlement terms must be confirmed through issuer channels.",
                ),
            ],
            execution_notes=[
                text_for_locale(
                    locale,
                    "把它当作通胀对冲腿时，应同时检查波动承受度和 T+3 赎回约束。",
                    "When using it as an inflation-hedge sleeve, check both volatility tolerance and the T+3 redemption constraint.",
                ),
            ],
            issuer_model="Hong Kong regulated silver RWA issuer with physical vault backing",
            holder_eligibility_note="Requires KYC level 2 (professional investor); minimum ticket $5,000",
            transfer_compliance_note="Transfer restricted per Hong Kong SFC compliance; whitelist-gated",
            redemption_custody_note="T+3 redemption; .9999 silver held in third-party vault with regular audits",
        ),
        AssetTemplate(
            asset_id="tokenized-real-estate-demo",
            symbol="RE-1",
            name="Tokenized Real Estate Demo",
            asset_type=AssetType.REAL_ESTATE,
            description=text_for_locale(
                locale,
                "用于 Hackathon 演示的房地产类 RWA 模板，突出申赎摩擦、分红收益与低流动性的组合特征。",
                "A hackathon real-estate RWA template that highlights redemption friction, income distribution, and structurally lower liquidity.",
            ),
            issuer="Demo SPV",
            custody="Offchain SPV / trustee structure",
            chain_id=chain_id,
            contract_address="",
            settlement_asset="USDT",
            execution_style="issuer_portal",
            benchmark_apy=0.078,
            expected_return_low=-0.05,
            expected_return_base=0.082,
            expected_return_high=0.14,
            price_volatility=0.18,
            max_drawdown_180d=0.15,
            avg_daily_volume_usd=160_000,
            redemption_days=7,
            lockup_days=30,
            management_fee_bps=110,
            entry_fee_bps=35,
            exit_fee_bps=35,
            slippage_bps=45,
            issuer_disclosure_score=0.58,
            custody_disclosure_score=0.62,
            audit_disclosure_score=0.55,
            contract_is_upgradeable=True,
            has_admin_key=True,
            oracle_count=1,
            oracle_sources=["issuer NAV"],
            requires_kyc_level=2,
            minimum_ticket_usd=25_000,
            tags=["rwa", "real-estate", "yield"],
            thesis=text_for_locale(
                locale,
                "收益看起来吸引人，但退出时间、法律结构和发行人治理是这类资产的主要风险源。",
                "The yield profile can look attractive, but exit timing, legal structure, and issuer governance dominate the risk.",
            ),
            fit_summary=text_for_locale(
                locale,
                "只适合能接受锁定期和条款尽调的人群。",
                "Only suitable for users who accept lockups and deeper term-sheet diligence.",
            ),
            evidence_urls=[HASHKEY_ABOUT_URL, HASHKEY_KYC_URL],
            primary_source_url=HASHKEY_ABOUT_URL,
            onchain_verified=False,
            issuer_disclosed=False,
            featured=False,
            statuses=[AssetStatus.DEMO, AssetStatus.EXPERIMENTAL],
            truth_level=TruthLevel.DEMO_ONLY,
            live_readiness=LiveReadiness.DEMO_ONLY,
            default_rank_eligible=False,
            status_explanation=text_for_locale(
                locale,
                "Hackathon 演示资产，用于展示高摩擦房地产 RWA 情形，不应默认与生产资产同台排名。",
                "Hackathon demo asset for a high-friction real-estate RWA case; it should not rank alongside production assets by default.",
            ),
            truth_level_explanation=text_for_locale(
                locale,
                "该模板用于演示报告结构和风险差异，不代表已验证的真实发行产品。",
                "This template exists to demonstrate reporting structure and risk trade-offs, not a verified live issuance.",
            ),
            action_type=ActionType.LEARN_MORE,
            action_readiness=ActionReadiness.UNAVAILABLE,
            action_links=_asset_action_links(
                chain_config,
                primary_source_url=HASHKEY_ABOUT_URL,
            ),
            action_blocker_reasons=[
                text_for_locale(
                    locale,
                    "Demo 资产默认不进入正式推荐排名，除非用户显式纳入非生产资产。",
                    "Demo assets are excluded from the default recommendation ranking unless the user explicitly includes non-production assets.",
                ),
                text_for_locale(
                    locale,
                    "没有可执行的真实申购入口或已验证合约。",
                    "There is no live subscription path or verified execution contract.",
                ),
            ],
            execution_notes=[
                text_for_locale(
                    locale,
                    "把它理解为条款压力测试样本，而不是可直接下单的产品。",
                    "Treat it as a term-sheet stress-test example rather than an asset you can directly subscribe to.",
                ),
            ],
            issuer_model="Demo SPV structure with offchain trustee; not fully disclosed",
            holder_eligibility_note="Requires KYC level 2; minimum ticket $25,000; accredited investor check",
            transfer_compliance_note="Highly restricted transfers; requires issuer approval per SPV terms",
            redemption_custody_note="T+7 to T+30 redemption; 30-day lockup; offchain SPV trustee custody",
        ),
        AssetTemplate(
            asset_id="hsk-wbtc-benchmark",
            symbol="WBTC",
            name="HashKey WBTC Benchmark",
            asset_type=AssetType.BENCHMARK,
            description=text_for_locale(
                locale,
                "HashKey Chain 官方列出的 WBTC 合约，用于给 RWA 方案增加一个高波动链上 benchmark。",
                "The WBTC contract listed by HashKey Chain, included as a high-volatility onchain benchmark for RWA comparisons.",
            ),
            issuer="Wrapped BTC bridge",
            custody="Bridge-backed BTC representation",
            chain_id=chain_id,
            contract_address="0x6119ca49a79f5825c8b345f8d7ac36b272565b14",
            settlement_asset="USDT",
            execution_style="erc20",
            benchmark_apy=0.0,
            expected_return_low=-0.22,
            expected_return_base=0.12,
            expected_return_high=0.35,
            price_volatility=0.62,
            max_drawdown_180d=0.36,
            avg_daily_volume_usd=2_400_000,
            redemption_days=0,
            lockup_days=0,
            management_fee_bps=0,
            entry_fee_bps=0,
            exit_fee_bps=0,
            slippage_bps=12,
            issuer_disclosure_score=0.66,
            custody_disclosure_score=0.64,
            audit_disclosure_score=0.6,
            contract_is_upgradeable=True,
            has_admin_key=True,
            oracle_count=2,
            oracle_sources=["market price feed", "bridge reserves"],
            requires_kyc_level=0,
            minimum_ticket_usd=100,
            tags=["benchmark", "volatile", "non-rwa-anchor"],
            thesis=text_for_locale(
                locale,
                "不是 RWA，但适合作为高波动机会成本基准，帮助用户理解为何 RWA 值得承担额外门槛。",
                "Not an RWA itself, but a useful high-volatility opportunity-cost benchmark for understanding why RWA gating may still be worthwhile.",
            ),
            fit_summary=text_for_locale(
                locale,
                "仅适合作为比较基准或进取型组合的小比例暴露。",
                "Primarily useful as a benchmark or as a small exposure inside more aggressive portfolios.",
            ),
            evidence_urls=[HASHKEY_TOKEN_CONTRACTS_URL, HASHKEY_NETWORK_INFO_URL],
            primary_source_url=HASHKEY_TOKEN_CONTRACTS_URL,
            onchain_verified=True,
            issuer_disclosed=True,
            featured=False,
            statuses=[AssetStatus.BENCHMARK, AssetStatus.VERIFIED],
            truth_level=TruthLevel.BENCHMARK_REFERENCE,
            live_readiness=LiveReadiness.READY,
            default_rank_eligible=False,
            status_explanation=text_for_locale(
                locale,
                "链上可执行的 benchmark，用来衡量机会成本和波动基线，不默认参与正式 RWA 推荐排名。",
                "An executable onchain benchmark used to frame opportunity cost and volatility, not a default candidate in formal RWA rankings.",
            ),
            truth_level_explanation=text_for_locale(
                locale,
                "合约本身可链上核验，但该资产在系统里承担 benchmark 参考角色。",
                "The contract itself is verifiable onchain, but the asset is treated here as a benchmark reference.",
            ),
            action_type=ActionType.HOLD,
            action_readiness=ActionReadiness.READY,
            action_links=_asset_action_links(
                chain_config,
                primary_source_url=HASHKEY_TOKEN_CONTRACTS_URL,
                contract_address="0x6119ca49a79f5825c8b345f8d7ac36b272565b14",
            ),
            action_blocker_reasons=[
                text_for_locale(
                    locale,
                    "默认只作 benchmark，不与生产型 RWA 候选同权竞争。",
                    "Shown as a benchmark by default rather than competing on equal footing with production-style RWA candidates.",
                ),
            ],
            execution_notes=[
                text_for_locale(
                    locale,
                    "若显式纳入比较，应把它理解为高波动机会成本锚点，而不是保守资金停泊位。",
                    "If explicitly included, treat it as a high-volatility opportunity-cost anchor rather than a conservative parking sleeve.",
                ),
            ],
            issuer_model="Wrapped BTC bridge representation on HashKey Chain",
            holder_eligibility_note="No KYC requirement; open to all wallet holders",
            transfer_compliance_note="Freely transferable ERC20; bridge operator retains admin key",
            redemption_custody_note="Redeemable via secondary markets; bridge-backed BTC custody",
        ),
    ]
